### PR TITLE
remove some magic numbers, clean up DCC ipv4/ipv6 global variable mess and use a union to save memory.

### PR DESCRIPTION
**Pull request by stefan11111**

### CODE REVIEW

**Comment by stefan11111** [comment]
Also fixed the TODO's in the code.

**Comment by stefan11111** [comment]
I have tried to fix this too, but I couldn't figure out how.
Do you have an idea how to write a patch that fixes it?
https://github.com/mcpcpc/kirc/issues/134

**Comment by stefan11111** [comment]
@mcpcpc I also made a patch to add support for sending files via DCC.
It works, but it's not in it's final form, as I'd like to clean up the code some more.
should I add the patch to this PR?
Or does it go against the suckless principles of this project?
https://github.com/stefan11111/kirc/pull/46

It's not added bloat, as all this does is when not using the feature is add an extra if check to the dcc slots.

**Comment by mcpcpc** [comment]
> @mcpcpc I also made a patch to add support for sending files via DCC.
> 
> It works, but it's not in it's final form, as I'd like to clean up the code some more.
> 
> should I add the patch to this PR?
> 
> Or does it go against the suckless principles of this project?
> 
> https://github.com/stefan11111/kirc/pull/46
> 
> 
> 
> It's not added bloat, as all this does is when not using the feature is add an extra if check to the dcc slots. 

I think it's acceptable "bloat".  My original intention was to maintain a minimal set of functionality while allowing the community to continue to drive added functionality through patches or other means.  With that said, the goal is to keep the project maintainable by one person.  Compared to other IRC clients, the CLOC is still low and the goal is to enhance existing DCC functionality.

**Comment by stefan11111** [comment]
@mcpcpc The DCC SEND code is mostly done.
I wonder if I should also do:
```
if (dcc) {
    signal(SIGPIPE, SIG_IGN);
}
```
So that the program doesn't crash if it receives a SIGPIPE in DCC?

**Comment by mcpcpc** [comment]
> @mcpcpc The DCC SEND code is mostly done. I wonder if I should also do:
> 
> ```
> if (dcc) {
>     signal(SIGPIPE, SIG_IGN);
> }
> ```
> 
> So that the program doesn't crash if it receives a SIGPIPE in DCC?

Yep.  That would probably be good 😆

**Comment by stefan11111** [comment]
@mcpcpc
I ended up fixing this too:
https://github.com/mcpcpc/kirc/issues/134

I have 2 patches for it.
patch1:
```
diff --git a/kirc.c b/kirc.c
index a4ebb69..d1cfaea 100644
--- a/kirc.c
+++ b/kirc.c
@@ -197,6 +197,10 @@ static void refresh_line(state l)
 {
     size_t plenu8 = l->plenu8 + 2;
     char *buf = l->buf;
+    for (buf = strchr(buf, '\t'); buf; buf = strchr(buf, '\t')) {
+        *buf = ' ';
+    }
+    buf = l->buf;
     size_t lenb = l->lenb;
     size_t posu8 = l->posu8;
     size_t ch = plenu8, txtlenb = 0;
```
patch2:
```
diff --git a/kirc.c b/kirc.c
index a4ebb69..0ed4165 100644
--- a/kirc.c
+++ b/kirc.c
@@ -197,6 +197,22 @@ static void refresh_line(state l)
 {
     size_t plenu8 = l->plenu8 + 2;
     char *buf = l->buf;
+    for (buf = strchr(buf, '\t'); buf; buf = strchr(buf, '\t')) {
+        int len1 = MSG_MAX - (buf - l->buf) - 1;
+        int len = strlen(buf);
+        memmove(buf + sizeof("    ") - 1, buf + 1, len < len1 ? len : len1);
+        l->buf[MSG_MAX] = '\0';
+        *buf = ' ';
+        *(buf + 1) = ' ';
+        *(buf + 2) = ' ';
+        *(buf + 3) = ' ';
+        l->lenb += sizeof("    ") - 2;
+        l->lenu8 += sizeof("    ") - 2;
+        l->posb += sizeof("    ") - 2;
+        l->posu8 += sizeof("    ") - 2;
+        l->buflen -= sizeof("    ") - 2;
+    }
+    buf = l->buf;
     size_t lenb = l->lenb;
     size_t posu8 = l->posu8;
     size_t ch = plenu8, txtlenb = 0;
```

The first patch treats '\t' as spaces, while the second one treats it as 4 spaces.
I prefer the first one, since it adds less complexity and keeping tabs as 1 space looks better imo.
which one, if any, should I add to this pr?

**Comment by stefan11111** [comment]
I ended up taking the first approach(with a different patch) and also treating '\031' as space, which was another character which would break the message buffer.

**Comment by mcpcpc** [comment]
@stefan11111 let me know when you are ready to merge.

**Comment by stefan11111** [comment]
@mcpcpc sure. I plan to look as some more things.
I'll let you know when I'm done.

**Pull request merged**
